# Saya Anandita K NIM 2101114 mengerjakan soal Latihan 4 dalam mata kulia h Desain dan Pemrograman Berorientasi Objek
# untuk keberkahanNya maka saya tidak melakukan kecurangan seperti yang telah dispesifikasikan. Aamiin.
from Prodi import Prodi
from Course import Course
from Mahasiswa import Mahasiswa
from Dosen import Dosen
# instansiasi objek dengan hardcode
course1 = Course("alpro", "01")
course2 = Course("MANBIS", "02")
course3 = Course("Dasar Boga", "03")

mhs1 = Mahasiswa()
mhs1.set_NIK("00000")
mhs1.set_NIM("2101114")
mhs1.set_Nama("anandita")
mhs1.set_Jenis_kelamin("perempuan")
mhs1.set_asal_universitas("UPI")
mhs1.set_fakultas("FPMIPA")
mhs1.set_email_edu("anandita@UPI.EDU")

mhs2 = Mahasiswa()
mhs2.set_NIK("00001")
mhs2.set_NIM("2101115")
mhs2.set_Nama("Do Kyungsoo")
mhs2.set_Jenis_kelamin("LAKI")
mhs2.set_asal_universitas("UPI")
mhs2.set_fakultas("FPMIPA")
mhs2.set_email_edu("Kyungsoo@upi.edu")

mhs3 = Mahasiswa()
mhs3.set_NIK("00002")
mhs3.set_NIM("2101116")
mhs3.set_Nama("Suho")
mhs3.set_Jenis_kelamin("LAKI")
mhs3.set_asal_universitas("UPI")
mhs3.set_fakultas("FPEB")
mhs3.set_email_edu("SUHOLKAY@upi.edu")

mhs4 = Mahasiswa()
mhs4.set_NIK("00003")
mhs4.set_NIM("2101117")
mhs4.set_Nama("Sohun")
mhs4.set_Jenis_kelamin("LAKI")
mhs4.set_asal_universitas("UPI")
mhs4.set_fakultas("FPTK")
mhs4.set_email_edu("sohunyamin@upi.edu")

dsn1 = Dosen()
dsn1.set_NIK("00004")
dsn1.set_NIP("1234567")
dsn1.set_Nama("KungFu")
dsn1.set_Jenis_kelamin("cowok")
dsn1.set_asal_universitas("UPI")
dsn1.set_fakultas("FPMIPA")
dsn1.set_email_edu("kungfu@upi.edu")
dsn1.set_pendidikan_terakhir("S3")
dsn1.set_keahlian("KODING 100 BAHASA")

dsn2 = Dosen()
dsn2.set_NIK("00005")
dsn2.set_NIP("2345678")
dsn2.set_Nama("pobi")
dsn2.set_Jenis_kelamin("cowok")
dsn2.set_asal_universitas("UPI")
dsn2.set_fakultas("FPEB")
dsn2.set_email_edu("pobi@upi.edu")
dsn2.set_pendidikan_terakhir("S2")
dsn2.set_keahlian("MANAJEMEN PERKANTORAN")

dsn3 = Dosen()
dsn3.set_NIK("00008")
dsn3.set_NIP("256784")
dsn3.set_Nama("papung")
dsn3.set_Jenis_kelamin("cowok")
dsn3.set_asal_universitas("UPI")
dsn3.set_fakultas("FPTK")
dsn3.set_email_edu("papung@upi.edu")
dsn3.set_pendidikan_terakhir("S2")
dsn3.set_keahlian("Pengolahan Makanan")

prodi1 = Prodi()
prodi1.set_nama_prodi("ILKOM")
prodi1.set_kode("1")
prodi1.course.append(course1)
prodi1.mahasiswa.append(mhs1)
prodi1.mahasiswa.append(mhs2)
prodi1.dosen.append(dsn1)

prodi2 = Prodi()
prodi2.set_nama_prodi("MANAJAEMEN BISNIS")
prodi2.set_kode("2")
prodi2.course.append(course2)
prodi2.mahasiswa.append(mhs3)
prodi2.dosen.append(dsn2)

prodi3 = Prodi()
prodi3.set_nama_prodi("TATA BOGA")
prodi3.set_kode("3")
prodi3.course.append(course3)
prodi3.mahasiswa.append(mhs4)
prodi3.dosen.append(dsn3)

list_prodi = []
list_prodi.append(prodi1)
list_prodi.append(prodi2)
list_prodi.append(prodi3)

# menampilkan data
for i in list_prodi:
    print("==========================================================")
    print("===", "List Program Studi".center(50), "===")
    print("===", i.get_nama_prodi().center(50), "===")
    print("===", i.get_kode().center(50), "===")
    print("==========================================================")
    for j in i.course:
        print("==========================================================")
        print("===", "List Mata Kuliah".center(50), "===")
        print("===", j.get_nama_matakuliah().center(50), "===")
        print("===", j.get_kode_matakuliah().center(50), "===")
        print("==========================================================")
        print("===", "Dosen".center(50), "===")
        print("==========================================================")
    for j in i.dosen:

        print(" NIK                : "+j.get_NIK())
        print(" NIP                : "+j.get_NIP())
        print(" Nama               : " + j.get_Nama())
        print(" Jenis Kelamin      : "+j.get_Jenis_kelamin())
        print(" Asal Universitas   : " + j.get_asal_universitas())
        print(" Fakultas           : " + j.get_fakultas())
        print(" Email Edu          : " + j.get_email_edu())
        print(" Pendidikan Terakhir: " + j.get_pendidikan_terakhir())
        print(" Keahlian           : " + j.get_keahlian())
        print()
    print("==========================================================")
    print("===", "Mahasiswa".center(50), "===")
    print("==========================================================")
    for j in i.mahasiswa:
        print(" NIK              : "+j.get_NIK())
        print(" NIM              : "+j.get_Nim())
        print(" Nama             : " + j.get_Nama())
        print(" Jenis Kelamin    : "+j.get_Jenis_kelamin())
        print(" Asal Universitas : " + j.get_asal_universitas())
        print(" Fakultas         : " + j.get_fakultas())
        print(" Email Edu        : " + j.get_email_edu())
        print()
